// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct SubscriptionContractProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for SubscriptionContractProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = SubscriptionContractProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        SubscriptionContractProxyMethods { wrapped_tx: tx }
    }
}

pub struct SubscriptionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> SubscriptionContractProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> SubscriptionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> SubscriptionContractProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn add_subscription_plan<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        title: Arg0,
        duration_days: Arg1,
        price: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u32> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addSubscriptionPlan")
            .argument(&title)
            .argument(&duration_days)
            .argument(&price)
            .original_result()
    }

    pub fn upgrade_subscription<
        Arg0: ProxyArg<u32>,
    >(
        self,
        new_plan_id: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("upgradeSubscription")
            .argument(&new_plan_id)
            .original_result()
    }

    pub fn add_new_subscription<
        Arg0: ProxyArg<u32>,
    >(
        self,
        plan_id: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("addNewSubscription")
            .argument(&plan_id)
            .original_result()
    }

    pub fn get_plan<
        Arg0: ProxyArg<u32>,
    >(
        self,
        plan_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<SubscriptionPlan<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPlan")
            .argument(&plan_id)
            .original_result()
    }

    pub fn get_subscription<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<Subscription<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSubscription")
            .argument(&user)
            .original_result()
    }

    pub fn get_all_plan_ids(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, u32>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAllPlanIds")
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, Debug)]
pub struct SubscriptionPlan<Api>
where
    Api: ManagedTypeApi,
{
    pub title: ManagedBuffer<Api>,
    pub price: BigUint<Api>,
    pub duration_days: u64,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, Debug)]
pub struct Subscription<Api>
where
    Api: ManagedTypeApi,
{
    pub plan_id: u32,
    pub started_at: u64,
    pub expires_at: u64,
    pub paid_amount: BigUint<Api>,
}
