// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback:                       1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tema_1
    (
        init => init
        upgrade => upgrade
        issueNft => issue_nft
        createNftWithAttributes => create_nft_with_attributes
        getYourNftCardProperties => get_your_nft_card_properties
        exchangeNft => exchange_nft
        getTokenId => get_token_id
        getTokenData => get_token_data
        tokenId => token_id
        nftSupply => nft_supply
        cardsProperties => cards_properties
        studentsCards => students_cards
        studentsAddresses => student_address
    )
}

multiversx_sc_wasm_adapter::async_callback! { tema_1 }
