// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            4
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tema_1
    (
        init => init
        upgrade => upgrade
        issueNft => issue_nft
        createNft => create_nft
        getTokenId => get_token_id
        tokenId => token_id
    )
}

multiversx_sc_wasm_adapter::async_callback! { tema_1 }
