// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    subscription
    (
        init => init
        upgrade => upgrade
        addSubscriptionPlan => add_subscription_plan
        upgradeSubscription => upgrade_subscription
        addNewSubscription => add_new_subscription
        getPlan => get_plan
        getSubscription => get_subscription
        getAllPlanIds => get_all_plan_ids
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
