---
title: "Blockchain Protocols and Distributed Applications"
subtitle: "Master's Curriculum"
author: ["Costin Carabaș"]
lang: en
geometry: margin=1in
fontsize: 11pt
documentclass: book
classoption:
  - twoside
  - openright
toc: true
toc-depth: 3
link-citations: true
urlcolor: blue
linkcolor: blue
colorlinks: false
links-as-notes: true
papersize: a4
header-includes:
  - \usepackage{hyperref}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{graphicx}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead{}
  - \fancyfoot{}
  - \fancyhead[LE,RO]{\thepage}
  - \fancyhead[RE]{Blockchain Protocols and Distributed Applications}
  - \fancyhead[LO]{Master's Curriculum}
publisher: "Politehnica University of Bucharest"
date: "2025"
version: "2025.0"
license: "Text: CC BY-NC-SA 4.0; Code: BSD-3-Clause"
---

