name: Build and Deploy Slides

on:
  push:
    branches:
      - main
    paths:
      - 'chapters/**/lecture/**'
      - 'common/makefile/**'
      - '.github/workflows/build-slides.yml'
      - 'Dockerfile'
  workflow_dispatch: # Allow manual triggering

jobs:
  build-deploy-slides:
    name: Build and Deploy Lecture Slides
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ./repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./repo
          file: ./repo/Dockerfile
          push: false
          load: true
          tags: bpda-slides:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare Output Directory
        run: |
          mkdir -p slides-output

      - name: Build Slides in Docker Container
        run: |
          # Build all lectures that have a Makefile
          docker run --rm \
            -v $GITHUB_WORKSPACE/repo:/content \
            -v $GITHUB_WORKSPACE/slides-output:/output \
            --entrypoint /bin/bash \
            bpda-slides:latest \
            -c '
              set -e
              echo "Building lecture slides..."
              
              # Find all lecture directories with Makefile
              for lecture_dir in /content/chapters/*/lecture; do
                if [ -f "$lecture_dir/Makefile" ]; then
                  echo "Building slides in: $lecture_dir"
                  cd "$lecture_dir"
                  make html || echo "Warning: Failed to build $lecture_dir"
                  
                  # Copy output to a named directory
                  chapter_name=$(basename $(dirname $(dirname "$lecture_dir")))
                  if [ -d "_site" ]; then
                    mkdir -p "/output/$chapter_name"
                    cp -r _site/* "/output/$chapter_name/"
                    echo "Copied slides for $chapter_name"
                  fi
                fi
              done
              
              echo "All slides built successfully!"
            '

      - name: Create Index Page
        run: |
          cat > slides-output/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Blockchain Protocols and Distributed Applications - Lecture Slides</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #f5f5f5;
              }
              h1 {
                color: #333;
                border-bottom: 3px solid #4CAF50;
                padding-bottom: 10px;
              }
              .lecture-list {
                list-style: none;
                padding: 0;
              }
              .lecture-item {
                background: white;
                margin: 15px 0;
                padding: 20px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                transition: transform 0.2s, box-shadow 0.2s;
              }
              .lecture-item:hover {
                transform: translateY(-2px);
                box-shadow: 0 4px 8px rgba(0,0,0,0.15);
              }
              .lecture-item a {
                color: #2196F3;
                text-decoration: none;
                font-size: 1.2em;
                font-weight: 500;
              }
              .lecture-item a:hover {
                color: #0D47A1;
              }
              footer {
                margin-top: 50px;
                text-align: center;
                color: #666;
                font-size: 0.9em;
              }
            </style>
          </head>
          <body>
            <h1>📚 Blockchain Protocols and Distributed Applications</h1>
            <h2>Lecture Slides</h2>
            <ul class="lecture-list">
          EOF
          
          # Add links for each built lecture
          for dir in slides-output/*/; do
            if [ -d "$dir" ]; then
              chapter=$(basename "$dir")
              # Capitalize first letter
              chapter_name=$(echo "$chapter" | sed 's/.*/\u&/')
              echo "    <li class=\"lecture-item\"><a href=\"$chapter/\">$chapter_name</a></li>" >> slides-output/index.html
            fi
          done
          
          cat >> slides-output/index.html << 'EOF'
            </ul>
            <footer>
              <p>Built with reveal.js | Generated by GitHub Actions</p>
            </footer>
          </body>
          </html>
          EOF

      - name: List Built Files (Debug)
        run: |
          echo "Contents of slides-output:"
          ls -laR slides-output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./slides-output
          publish_branch: gh-pages
          destination_dir: slides
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy lecture slides'

